
gcc -O3 -Wall -c -Isrc -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/ -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/ -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/htslib -rdynamic -o cnvdata.o -L/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/ -L/nfs/ddd0/Tom/cram/cram/samtools-1.2/ cnvdata.c -lhts -lbam -lpthread -lz -lm

g++ -I . -c gc.cpp 
g++ -I . -c cwavef.cpp 
g++ -I . -c adms.cpp 
g++ -I . -c rd.cpp 
g++ -I . -c fh.cpp 
g++ -I . -c util.cpp 
g++ -I . -c -Isrc -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/ -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/ -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/htslib readdata.cpp -lhts -lbam -lpthread -lz -lm
g++ -I . -c -Isrc -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/ -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/ -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/htslib ngscnv.cpp -lhts -lbam -lpthread -lz -lm


g++ -Isrc -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/ -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/ -I/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/htslib -rdynamic -o ngs ngscnv.o gc.o cwavef.o fh.o util.o adms.o readdata.o cnvdata.o -L/nfs/ddd0/Tom/cram/cram/samtools-1.2/htslib-1.2.1/ -L/nfs/ddd0/Tom/cram/cram/samtools-1.2/ -lhts -lbam -lpthread -lz -lm



